ROI: 1.2
batch_size: 64
conv_threshold: 1.0e-05
epochs: 300
loss_fn: !!python/name:torch.nn.modules.loss.NLLLoss ''
lr_high: 0.001
lr_low: 0.0001
minibatch_length: 5
minibatch_stride: 2
network_size: 32
optimizer: !!python/name:torch.optim.adagrad.Adagrad ''
patience: 30
train_test_split: 0.7
wh: 160
